---
title: "Crime map"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    theme: journal
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(plotly)

knitr::opts_chunk$set(
  fig.width = 10,
  fig.asp = .2,
  out.width = "90%",
  dpi = 300
)
```

```{r}
library(readxl)
library(lubridate)
```

```{r, message=FALSE, warning=FALSE}
crime_df = read_csv("data/crime_df.csv")
head(crime_df)
```

```{r, message=FALSE}
crime_plot =
  crime_df %>% 
  filter(!is.na(borough)) %>%
  plot_ly(
    lat = ~latitude, 
    lon = ~longitude, 
    frame = ~hour_of_day,
    type = "scattermapbox", 
    mode = "markers", 
    alpha = 0.2,
    color = ~borough) %>% 
  layout(
    mapbox = list(
      style = 'carto-positron',
      zoom = 9,
      center = list(lon = -73.9, lat = 40.7)))
crime_plot
```

# Map based on zipcodes

```{r}
library(sp)
library(rgdal)
```

```{r}
#import zips shapefile and transform CRS 
zips <- readOGR("cb_2015_us_zcta510_500k/cb_2015_us_zcta510_500k.shp")
zips <- spTransform(zips, CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
```

```{r}
#define crime_df_map for our map
crime_df_map = drop_na(crime_df, latitude)

#extract only lon and lat
crime_lat_long = select(crime_df_map, longitude, latitude)

#transform coordinates into a SpatialPointsDataFrame
crime_spdf = SpatialPointsDataFrame(coords = crime_lat_long, data = crime_lat_long, proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))

#subset only the zipcodes in which points are found
crime_zips <- zips[crime_spdf, ]

#redefine crime_df_map to include zipcodes
crime_df_map$zip <- over(crime_spdf, crime_zips[,"ZCTA5CE10"])
```

