---
title: "Report"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: journal
---

## Motivation

## Related Work

## Initial Questions

## Data

In Our project, there are two datasets, including NYPD Complaint Data Historic 
and weather data.  We obtained crime data in New York City from NYC Open Data
* Crime data of New York City is downloaded from the link below :
[NYPD Complaint Data Historic](https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i).

This dataset contains 780 million felony, misdemeanor, and violation crimes 
reported to the New York City Police Department (NYPD) from 1910 to 2021. Each 
record contains detailed information of a single crime reported to NYPD. 
In our project, we select the records from 2016-01-01 to 2017-12-31 to do 
analysis and modeling.

For further analysis, we converted the original dataset to make it more readable
and  selected some key variables:

  * `date`. Date the crime occurs.
  * `hour_of_day`. Occurring time of the crimes
  * `borough`. Borough the crime occurs.
  * `level`. Level of offense: felony, misdemeanor, violation.
  * `offense`. Description of offense.
  * `offense_classification`. Description of internal classification of offense.
  * `place`. Specific description of premises; grocery store, residence,street, etc.
  * `suspect_age`. Suspect’s Age Group.
  * `suspect_race`. Suspect’s Race Description.
  * `suspect_sex`. Suspect’s Sex Description.
  * `victim_age`. Victim’s Age Group.
  * `victim_race`. Victim’s Race Description.
  * `victim_sex`. Victim’s Sex Description.
  * `day_of_week`. Day of week that a crime occurs.
  * `mon`. Months in a year that a crime occurs.
  * `latitude`. Latitude of the place the crime occurs.
  * `longitude`. Longitude of the place the crime occurs.

Considering that weather may be a reason of committing crime, we used data from 
three weather stations in New York and calculate the mean weather parameters to 
represent the weather of New York.

Weather data is obtained from website of [NOAA](https://www.ncei.noaa.gov/metadata/geoportal/rest/metadata/item/gov.noaa.ncdc:C00861/html)

The key variables of weather are:

  * `mean_snow`. snow depth(mm).
  * `mean_prcp`. precipitation(tenths of mm)
  * `mean_tmin`. minimum temperature of a day
  * `mean_tmax`. maximum temperature of a day


## Exploratory Analysis

## Statistical Analysis

#### Statistical test
We want to explore more on our data. So we conducted some statistical test.
First, we conducted a Chi-squared test on year and number of cases each month to 
check whether the distribution of number of cases per month is different between
the two years. The result shows that there is a significant difference of 
distribution between the two years. 

And then we want to investigate whether weather is a significant factor on number 
of crime cases. We combine the two dataset and create a categorical variable 
according to the weather parameters each day and devided them into four types:
"rainy and snowy", "snowy", "rainy", "not rainy or snowy". After that, we 
conducted a ANOVA test between number of crimes per day and weather. From the 
result, we came to conclude that the the average number of crimes per day is 
significantly different in different weather. 

We also conducted a Chi-squared test on number of different types of crimes and 
weather. We learned from the result that there is not a homogeneity in the types 
of crimes for each type of weather. So we conclude that weather may also has an 
association with the type of crimes.

#### Modeling

We already know that weather may influence crimes from previous analysis. So we 
decided to build a model to predict daily crimes cases. We proposed following
models:

* Model1: total_crime ~  day_of_week + mean_tmax + mean_prcp + mean_snow
* Model2: total_crime ~ month +day_of_week +  mean_tmax + mean_prcp + mean_snow
* Model3: total_crime ~  month +day_of_week +  mean_tmax + mean_prcp + mean_snow + mean_tmax*day_of_week
* Model4: total_crime ~ mean_tmax + mean_prcp + mean_snow

We use cross validation to compare the four models and performed a diagnostics 
and we concluded that Model3 is the best and it meet the model assumptions. 
We should select month, day of week, maximum temperature, precipitation, snow depth 
and a interaction term between temperature as our predictors.



## Discussion

