<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Report</title>

<script src="site_libs/header-attrs-2.16/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/journal.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="Clean-data.html">Data</a>
</li>
<li>
  <a href="statistical-test.html">Statistical Test</a>
</li>
<li>
  <a href="Modeling.html">Modeling</a>
</li>
<li>
  <a href="Report.html">Report</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Interaction Maps
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="map.html">Crime Maps</a>
    </li>
    <li>
      <a href="https://liyc5215.shinyapps.io/r_shiny_map/">Crime Map shiny</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://zz2780.shinyapps.io/final_shiny/">Offenses Shiny</a>
</li>
<li>
  <a href="https://github.com/zz2780/crimeweather_final_project.github.io">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="mailto:&lt;hw2861@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://spotcrime.com">
    <span class="fa fa-solid fa-bell"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Report</h1>

</div>


<div id="motivation" class="section level2">
<h2>Motivation</h2>
<p>Based on the Lombroso’s Theory of Crime, natural climatic factors can
influence crime rates. The Extreme temperatures sap one’s energy and
reduce the passion for crime. The suitable temperatures stimulate one’s
nerve like alcohol and makes it easier to commit criminal acts in an
excited situation.</p>
<p>In fact, the weather in criminology covers many aspects. Apart from
the weather itself, it also involves the seasons as well as the
temperature. All of these natural events occur in the spatial and
temporal dimensions and recur with regularity from year to year
constitutes a season. In order to fully discuss the changes of crime
rates in the time dimension, we also consider the changes in crime rates
at different times of the day and on different days of the week.</p>
</div>
<div id="initial-questions" class="section level2">
<h2>Initial Questions</h2>
<p>The initial question we want to investigate is if weather can have an
effect on crime rates. As we collected the data, we discovered that the
dataset also include the time and date of each crime. This discovery led
us to the discussion whether different time of the day or day of the
week can impact crime rates.</p>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<p>In Our project, there are two datasets, including NYPD Complaint Data
Historic and weather data. We obtained crime data in New York City from
NYC Open Data * Crime data of New York City is downloaded from the link
below : <a
href="https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i">NYPD
Complaint Data Historic</a>.</p>
<p>This dataset contains 780 million felony, misdemeanor, and violation
crimes reported to the New York City Police Department (NYPD) from 1910
to 2021. Each record contains detailed information of a single crime
reported to NYPD. In our project, we select the records from 2016-01-01
to 2017-12-31 to do analysis and modeling.</p>
<pre class="r"><code>crime_raw &lt;- read.csv(&quot;data/nyc_complaint_data.csv&quot;)
crime_df &lt;- crime_raw %&gt;%
  janitor::clean_names() %&gt;%
  mutate(
    date = mdy(cmplnt_fr_dt),
    hour_of_day = as.POSIXct(cmplnt_fr_tm, format=&quot;%H:%M:%OS&quot;),
    borough = boro_nm,
    level = law_cat_cd,
    offense = ofns_desc,
    offense_classification = pd_desc,
    place = prem_typ_desc,
    suspect_age = susp_age_group,
    suspect_race = factor(susp_race),
    victim_age = vic_age_group,
    victim_race = factor(vic_race)) %&gt;%
  mutate(
    day_of_week = factor(weekdays(date)),
    mon = month(date),
    hour_of_day = hour(hour_of_day)
  )


crime_df &lt;- crime_df %&gt;%
 select(date:mon, latitude,longitude)</code></pre>
<p>For further analysis, we converted the original dataset to make it
more readable and selected some key variables:</p>
<ul>
<li><code>date</code>. Date the crime occurs.</li>
<li><code>hour_of_day</code>. Occurring time of the crimes</li>
<li><code>borough</code>. Borough the crime occurs.</li>
<li><code>level</code>. Level of offense: felony, misdemeanor,
violation.</li>
<li><code>offense</code>. Description of offense.</li>
<li><code>offense_classification</code>. Description of internal
classification of offense.</li>
<li><code>place</code>. Specific description of premises; grocery store,
residence,street, etc.</li>
<li><code>suspect_age</code>. Suspect’s Age Group.</li>
<li><code>suspect_race</code>. Suspect’s Race Description.</li>
<li><code>victim_age</code>. Victim’s Age Group.</li>
<li><code>victim_race</code>. Victim’s Race Description.</li>
<li><code>day_of_week</code>. Day of week that a crime occurs.</li>
<li><code>mon</code>. Months in a year that a crime occurs.</li>
<li><code>latitude</code>. Latitude of the place the crime occurs.</li>
<li><code>longitude</code>. Longitude of the place the crime
occurs.</li>
</ul>
<p>Considering that weather may be a reason of committing crime, we used
data from three weather stations in New York and calculate the mean
weather parameters to represent the weather of New York.</p>
<p>Weather data is obtained from website of <a
href="https://www.ncei.noaa.gov/metadata/geoportal/rest/metadata/item/gov.noaa.ncdc:C00861/html">NOAA</a>.</p>
<p>We selected the three weather stations that can indicate the weather
in Manhattan. And we created average_weather dataset to see the mean
temperature, percipitation, and snowfall for each day.</p>
<pre class="r"><code>weather = rnoaa::meteo_pull_monitors(
    c(&quot;USW00094728&quot;, &quot;USW00094789&quot;, &quot;USW00014732&quot;),
    var = c(&quot;PRCP&quot;, &quot;SNOW&quot;, &quot;SNWD&quot;, &quot;TMAX&quot;, &quot;TMIN&quot;),
    date_min = &quot;2016-01-01&quot;,
    date_max = &quot;2017-12-31&quot;) %&gt;%
  mutate(
    id=case_when(
      id==&quot;USW00094728&quot; ~ &quot;CentralPark_NY&quot;, 
      id==&quot;USW00094789&quot; ~ &quot;JFK Airport_NY&quot;,
     id==&quot;USW00014732&quot; ~ &quot;La Guardia_NY&quot;),
    
    
    tmin = tmin / 10,
    tmax = tmax / 10) %&gt;%
  select(id, everything())

average_weather &lt;- weather %&gt;% 
  group_by(date) %&gt;%
  summarise(
    mean_snow = mean(snwd),
    mean_prcp = mean(prcp),
    mean_tmin = mean(tmin),
    mean_tmax = mean(tmax)
  ) </code></pre>
<p>The key variables of weather are:</p>
<ul>
<li><code>mean_snow</code>. snow depth(mm).</li>
<li><code>mean_prcp</code>. precipitation(tenths of mm)</li>
<li><code>mean_tmin</code>. minimum temperature of a day</li>
<li><code>mean_tmax</code>. maximum temperature of a day</li>
</ul>
</div>
<div id="exploratory-analysis" class="section level2">
<h2>Exploratory Analysis</h2>
<p>Based on some publicly available information, we knew that weather
affect crime rate. For example, the hotter the weather is, the more
likely people are to commit crimes. The worse the weather is, the less
likely people are to go out and commit crimes. Here we want to predict
number of crimes each day in New York as our outcome. And the
precipitation, snow depth, maximum temperature and minimum temperature
can be considered as predictors.</p>
<p>First we created a new dataset from the original crime_df dataset,
grouped by date, month, and day of the week and summarized the total
number of crimes. Then we merged it with weather dataset by date</p>
<pre class="r"><code>new_crime_df = crime_df %&gt;%
  group_by(date,mon,day_of_week)%&gt;%
  summarize(
    total_crime = n(),
    ) 

crime_weather = merge(new_crime_df, average_weather, by = &quot;date&quot;)
crime_weather &lt;- crime_weather %&gt;%
  mutate(
    month = factor(mon)
  )</code></pre>
<p>We first checked the distribution of number of crime cases each day
in New York.</p>
<pre class="r"><code>ggplot(data = crime_weather,aes(x = total_crime)) + geom_histogram()+ 
  labs(title = &quot;The distribution of daily cases&quot;, 
       y = &quot;Counts&quot;, 
       x = &quot;Number of crimes per day&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-5-1.png" width="768" /></p>
<p>The distribution of daily cases is approximately normally
distributed, thus we do not need to transform the value of the
outcome.</p>
<p>Then, we use scatter plot to investigate the association between
weather and cases/crime. The predictors for weather included minimum and
maximum temperature, percipitation and snowfall.</p>
<pre class="r"><code>ggplot(crime_weather, aes(x = mean_tmax, y = total_crime)) + geom_point()+    labs(title = &quot;The Association between Max temperatures and reported crime&quot;, 
       y = &quot;Total Crime reported&quot;, 
       x = &quot;Max temperatures of a day&quot;)+
    theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-6-1.png" width="768" /></p>
<pre class="r"><code>ggplot(crime_weather, aes(x = mean_tmin, y = total_crime)) + geom_point()+    labs(title = &quot;The Association between Min temperatures and reported crime&quot;, 
       y = &quot;Total Crime reported&quot;, 
       x = &quot;Min temperatures of a day&quot;)+
    theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-6-2.png" width="768" /></p>
<pre class="r"><code>ggplot(crime_weather, aes(x = mean_prcp, y = total_crime)) + geom_point()+    labs(title = &quot;The Association between precipitation and reported crime&quot;,
       y = &quot;Total Crime reported&quot;, 
       x = &quot;Precipitation(tenths of mm)&quot;)+
    theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-6-3.png" width="768" /></p>
<pre class="r"><code>ggplot(crime_weather, aes(x = mean_snow, y = total_crime)) + geom_point()+    labs(title = &quot;The Association between snowfall and reported crime&quot;,
       y = &quot;Total Crime reported&quot;, 
       x = &quot;Snow depth(mm)&quot;)+
    theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-6-4.png" width="768" /></p>
<p>From the plots, we noticed that all of the four predictors may have
association with the number of cases of crime in New York. Association
between crimes and min/max temperature have a more obvious linear trend,
whereas that between crimes and precipitation and snow depth have a less
obvious trend.</p>
<p>We also want to investigate whether the month, day of week, and hour
of the day can be predictors.</p>
<pre class="r"><code># Crime numbers by month

crime_month = new_crime_df %&gt;% 
     group_by(mon) %&gt;%
     summarize(mean_total_crimes = mean(total_crime)) %&gt;%
                 rename(month = mon) %&gt;% 
                 mutate(month = as.character(month))
 
mp = ggplot(crime_month,
        aes(x = month, y = mean_total_crimes, fill = month)) +
   geom_col(fill = &quot;lightblue&quot;,colour = &quot;steelblue&quot;) +
   geom_text(aes(label = round(mean_total_crimes)), vjust = -0.5, size=3 ) +
   labs(x=&quot;Month&quot;, 
        y=&quot;Number of Crimes&quot;,
        title = &quot;Average Total Number of Crimes 
        By Month In 2016 &amp; 2017&quot;)+
   scale_x_discrete(limits=crime_month$month)+
   theme_bw()+
   theme(legend.position = &quot;off&quot;, plot.title=element_text(hjust=0.5))
 
mp</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-7-1.png" width="768" /></p>
<pre class="r"><code>#Crime and weekdays

crime_weekday = new_crime_df %&gt;% 
  group_by(day_of_week) %&gt;% 
  summarise(mean_crime = round(mean(total_crime),0)) %&gt;% 
  mutate(char = case_when(day_of_week == &quot;Monday&quot; ~ 01, 
                          day_of_week == &quot;Tuesday&quot; ~ 02,
                          day_of_week == &quot;Wednesday&quot; ~ 03, 
                          day_of_week == &quot;Thursday&quot; ~ 04,
                          day_of_week == &quot;Friday&quot; ~ 05,
                          day_of_week == &quot;Saturday&quot; ~ 06,
                          day_of_week == &quot;Sunday&quot; ~ 07)) %&gt;%
  arrange(char) %&gt;% select(-char)

weekday = ggplot(crime_weekday,
       aes(x = day_of_week, y = mean_crime, fill = day_of_week, alpha=0.2)) +
  geom_col() +
  geom_text(aes(label = mean_crime), vjust = -0.5) + 
  labs(x=&quot;Day of Week&quot;, 
       y=&quot;Number of Crimes&quot;,
       title = &quot;Average Total Number of Crimes
       Each Week In 2016 &amp; 2017&quot;) +
  scale_x_discrete(limits=crime_weekday$day_of_week) +
  theme_bw() +
  theme(legend.position = &quot;off&quot;, plot.title=element_text(hjust=0.5))
  
weekday</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-7-2.png" width="768" /></p>
<pre class="r"><code>#Crime and hours

crime_hour = crime_df %&gt;%
  group_by(date,mon,day_of_week, hour_of_day)%&gt;%
  summarize(
    total_crime = n(),
    ) %&gt;%
  group_by(hour_of_day) %&gt;% 
  summarize(mean_crime = mean(total_crime))

crime_hour_plot = ggplot(crime_hour,
       aes(x = hour_of_day, y = mean_crime, fill = hour_of_day, alpha=0.2)) +
  geom_col(fill = &quot;plum4&quot;, colour = &quot;powderblue&quot;) +
  labs(x=&quot;Hour of Day&quot;, 
       y=&quot;Average Number of Crimes&quot;,
       title = &quot;Average Total Number of Crimes In 24 Hours
        Per Day In 2016 &amp; 2017&quot;) +
  scale_x_discrete(limits=crime_hour$hour_of_day) +
  theme_bw() +
  theme(legend.position = &quot;off&quot;, plot.title=element_text(hjust=0.5))
  
crime_hour_plot</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-7-3.png" width="768" /></p>
<p>We can observe that number of crimes slightly decreases during the
month from January to March and remains constant for the rest of year.
And number of crimes fluctuate when comparing each day of the week.
Friday and Wednesday have relatively higher number of crimes in average.
When comparing each hour of the day, we can see that during the hour
from 1AM to 11AM, the number of crimes is lower than the rest of the
day, with 5AM and 6AM have the lowest number of crimes in average.</p>
<div id="interactive-map" class="section level4">
<h4>Interactive Map</h4>
<p>We first created a map on the spatial distribution of crime incidents
in different time period of the day, but we want to see the distribution
of crimes within each zip code for more practical purpose.</p>
<pre class="r"><code>#read crime_df data
crime_df = read_csv(&quot;data/crime_df.csv&quot;) %&gt;%
  janitor::clean_names() %&gt;%
  rename(case_number = x1)

#define crime_df_map for our map
crime_df_map = drop_na(crime_df, latitude)</code></pre>
<pre class="r"><code>crime_plot =
  crime_df %&gt;% 
  filter(!is.na(borough)) %&gt;%
  plot_ly(
    lat = ~latitude, 
    lon = ~longitude, 
    frame = ~hour_of_day,
    type = &quot;scattermapbox&quot;, 
    mode = &quot;markers&quot;, 
    alpha = 0.2,
    color = ~borough) %&gt;% 
  layout(
    title = &quot;Spatial distribution of crime incidents&quot;,
    mapbox = list(
      style = &#39;carto-positron&#39;,
      zoom = 9,
      center = list(lon = -73.9, lat = 40.7)),
    legend = list(title=list(text=&#39;&lt;b&gt; Borough &lt;/b&gt;&#39;))
    ) %&gt;%
  animation_slider(
    currentvalue = list(prefix = &quot;Hour of day: &quot;, font = list(color=&quot;black&quot;))
  )</code></pre>
<p>Crime rate for a zip code region is defined as number of crime
incidents occurred in the zip code region during 2016-01-01 and
2017-12-31, divided by population size in the corresponding zip code
region. We matched each crime incident to a zip code using its
coordinates (longitude and latitude). 300 crimes cannot be matched to a
zip code and thus were dropped.</p>
<pre class="r"><code>zips = readOGR(&quot;data/cb_2015_us_zcta510_500k/cb_2015_us_zcta510_500k.shp&quot;, verbose=FALSE)
zips = spTransform(zips, CRS(&quot;+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0&quot;))

#extract only lon and lat
crime_lat_long = select(crime_df_map, longitude, latitude)

#transform coordinates into a SpatialPointsDataFrame
crime_spdf = SpatialPointsDataFrame(coords = crime_lat_long, data = crime_lat_long, proj4string = CRS(&quot;+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0&quot;))

#subset only the zipcodes in which points are found
crime_zips = zips[crime_spdf, ]

#redefine crime_df_map to include zipcodes
crime_df_map = cbind(crime_df_map, over(crime_spdf, crime_zips[,&quot;ZCTA5CE10&quot;]))
crime_df_map = rename(crime_df_map, zip = ZCTA5CE10)

#300 crime incidents can’t be matched to a zip code, so we drop them.
crime_df_map =
  crime_df_map %&gt;%
  drop_na(zip)</code></pre>
<p>In order to make meaningful data analysis, we want zip codes to
represent regions with similar population. However, some zip code
regions are very small, among which there are even some buildings that
have their own zip codes. To deal with the challenges of zip codes, we
convert zip codes to modified zip codes to account for discrepancies in
population size. Modified zip codes represent regions with similar
population size.</p>
<pre class="r"><code>zcta_conv = read_csv(&quot;data/ZCTA-to-MODZCTA.csv&quot;)
zcta_conv$ZCTA = as.character(zcta_conv$ZCTA)
zcta_conv$MODZCTA = as.character(zcta_conv$MODZCTA)

# match the zipcode in the original dataset to the modified zip code.
crime_df_map = crime_df_map %&gt;%
  left_join(rename(zcta_conv, zip = ZCTA), by = &quot;zip&quot;) %&gt;%
  rename(mod_zip = MODZCTA)

#4 crimes cannot be matched to a modifed zip code.
crime_df_map = drop_na(crime_df_map, mod_zip)

# shapefifle based on modified zip code
modzcta = st_read(&quot;data/MODZCTA_2010/MODZCTA_2010.shp&quot;, quiet=TRUE) %&gt;%
  janitor::clean_names()

# merge files
crime_df_geo =
  geo_join(modzcta, crime_df_map, &quot;modzcta&quot;, &quot;mod_zip&quot;, how = &quot;inner&quot;) %&gt;%
  rename(mod_zip = modzcta)</code></pre>
<p>Based on the dataset obtained above, we can get number of crimes in
each zip region.</p>
<pre class="r"><code>number_of_crimes = 
  crime_df_geo %&gt;% 
  group_by(mod_zip) %&gt;% 
  summarize(number_of_crimes = n()) %&gt;%
  arrange(desc(number_of_crimes))
head(number_of_crimes)</code></pre>
<pre><code>## Simple feature collection with 6 features and 2 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 996000 ymin: 172000 xmax: 1020000 ymax: 270000
## Projected CRS: Lambert_Conformal_Conic
## # A tibble: 6 × 3
##   mod_zip number_of_crimes                                              geometry
##   &lt;chr&gt;              &lt;int&gt;                       &lt;MULTIPOLYGON [US_survey_foot]&gt;
## 1 11212               2125 (((1005996 177746, 1005954 177710, 1005926 177744, 1…
## 2 11207               2114 (((1012026 179982, 1011954 179986, 1011812 179962, 1…
## 3 11208               2044 (((1019242 174790, 1019054 174514, 1019026 174530, 1…
## 4 10467               1911 (((1017492 255688, 1017464 255668, 1017336 255972, 1…
## 5 10456               1899 (((1010978 237664, 1010960 237576, 1010546 237332, 1…
## 6 10029               1806 (((997976 225838, 997840 225592, 997478 225792, 9974…</code></pre>
<p>As to crime crate, we obtained population of each zip code region
from World Population Review.</p>
<pre class="r"><code>pop_zip = read_csv(&quot;data/csvData.csv&quot;) %&gt;%
  janitor::clean_names()
pop_zip$zip = as.character(pop_zip$zip)

#filter out regions in New York City
pop_zip = pop_zip %&gt;%
  filter(county %in% c(&quot;New York&quot;, &quot;Kings&quot;, &quot;Queens&quot;, &quot;Bronx&quot;, &quot;Richmond&quot;))

# manually added zip code 10065 because missing (data from Census Reporter)
pop_zip[nrow(pop_zip) + 1,] = list(&quot;10065&quot;,&quot;    
New York City&quot;, &quot;New York&quot;, 30339)</code></pre>
<p>After converting the zip code to the modified one and got the
population from each region, we merged population file with the number
of crimes calculated before and calculated the crime rates.</p>
<pre class="r"><code>pop_mod_zip = pop_zip %&gt;%
  left_join(rename(zcta_conv, zip = ZCTA), by = &quot;zip&quot;) %&gt;%
  rename(mod_zip = MODZCTA) %&gt;%
  group_by(mod_zip) %&gt;%
  summarize(population = sum(population))

crime_rate = left_join(number_of_crimes, pop_mod_zip, by = &quot;mod_zip&quot;)
crime_rate$crime_rate = crime_rate$number_of_crimes / crime_rate$population * 100
crime_rate = 
  crime_rate %&gt;%
  select(mod_zip, crime_rate) %&gt;%
  group_by(crime_rate) %&gt;%
  arrange(desc(crime_rate))
head(crime_rate)</code></pre>
<pre><code>## Simple feature collection with 6 features and 2 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 979000 ymin: 194000 xmax: 999000 ymax: 223000
## Projected CRS: Lambert_Conformal_Conic
## # A tibble: 6 × 3
## # Groups:   crime_rate [6]
##   mod_zip crime_rate                                                    geometry
##   &lt;chr&gt;        &lt;dbl&gt;                             &lt;MULTIPOLYGON [US_survey_foot]&gt;
## 1 10075        11.2  (((998794 219854, 998630 219622, 998616 219632, 998598 219…
## 2 10018         9.00 (((982886 215080, 982752 214836, 982664 214676, 982630 214…
## 3 10001         6.23 (((987646 210360, 987522 210136, 987296 210262, 987334 210…
## 4 10004         6.19 (((982030 197212, 981958 197118, 981652 197444, 981784 197…
## 5 10006         5.61 (((980782 196772, 980576 196444, 980358 196542, 980276 196…
## 6 10036         4.96 (((985182 215442, 985136 215360, 985084 215414, 984866 215…</code></pre>
<p>Finally, the interactive map that shows the crime rates in the five
boroughs of New York City according to zip code region can be found <a
href="https://zz2780.github.io/crimeweather_final_project.github.io/map.html#">here</a>.
We can observe that in the years of 2016 and 2017, zip code 10075 has
the highest crime rate. Zip code 10018 and 10001 also have relatively
high crime rates. And Manhattan in general contains zipcode region of
highest crime rates.</p>
<pre class="r"><code>#label
labels = sprintf(
  &quot;&lt;strong&gt;%s&lt;/strong&gt;&lt;br/&gt;Crime rate is %g&amp;percnt;&lt;br/&gt;during the period from 2016-01-01 to 2017-12-31.&quot;, crime_rate$mod_zip, crime_rate$crime_rate) %&gt;%
  lapply(htmltools::HTML)

#color palette
pal = colorBin(palette = &quot;OrRd&quot;, 9, domain = crime_rate$crime_rate)

map_interactive = crime_rate %&gt;%
  st_transform(crs = &quot;+init=epsg:4326&quot;) %&gt;%
  leaflet() %&gt;%
  addProviderTiles(provider = &quot;CartoDB.Positron&quot;) %&gt;%
  addPolygons(label = labels,
              stroke = FALSE,
              smoothFactor = 0.5,
              opacity = 1,
              fillOpacity = 0.7,
              fillColor = ~ pal(crime_rate),
              highlightOptions = highlightOptions(weight = 5,
                                                  fillOpacity = 1,
                                                  color = &quot;black&quot;,
                                                  opacity = 1,
                                                  bringToFront = TRUE)) %&gt;%
  addLegend(&quot;bottomright&quot;,
            pal = pal,
            values = ~ crime_rate,
            title = &quot;Crime cases per 100 residents&lt;br/&gt;during the period from&lt;br/&gt;2016-01-01 to 2017-12-31&quot;,
            opacity = 0.7) %&gt;%
  addTiles(&quot;Interactive map of crime rate&quot;)
#saveWidget(map_interactive, &quot;nyc_crime_rate_map.html&quot;)</code></pre>
<p>To display our results in a more interesting way, we created a shiny
app which shows crime counts and rate in each modified zip code region
for every 4-week interval. The link to shiny app can also be accessed
with the same link above.</p>
<pre class="r"><code>crime_month = readRDS(&quot;crime_month.RDS&quot;)

#define UI
ui = fluidPage(
  titlePanel(&quot;NYC crime visualization by 4 weeks interval and modified zip code regions&quot;),
  sidebarLayout(
    sidebarPanel(
      h5(&quot;Data metrics are aggregated by 4 weeks and categorized by the first day in the 4 weeks interval. Data metrics are grouped into modified zip code regions instead of standard zip code regions to account for the discrepant population size in different standard zip code regions. Crime counts for a modified zip code region is the aggregated number of crime incidents occurred in the modified zip code region during the 4 weeks period starting from the specified date. Crime rate is the corresponding crime counts divided by the population size in the corresponding modified zip code region.&quot;),
      selectInput(
        &quot;date&quot;,
        &quot;Select a date (a 4 weeks period starting from):&quot;,
        choices = unique(crime_month$month_following)
      )
    ),
    mainPanel(
      tabsetPanel(
        tabPanel(&quot;Crime counts&quot;, leafletOutput(&quot;crime_counts&quot;)),
        tabPanel(&quot;Crime rate&quot;, leafletOutput(&quot;crime_rate&quot;))
      )
    )
  )
)

#define server logic
server &lt;- function(input, output){
  month_selected &lt;- reactive({
    w &lt;- crime_month %&gt;%
      filter(month_following == input$date)
    return(w)
  })
  output$crime_counts &lt;- renderLeaflet({
    pal &lt;- colorBin(palette = &quot;YlGn&quot;, 9, domain = crime_month$crime_counts)
    labels = sprintf(
      &quot;&lt;strong&gt;%s&lt;/strong&gt;&lt;br/&gt;%g incidents during the 4 weeks period&quot;,
      month_selected()$modzcta, month_selected()$crime_counts) %&gt;%
      lapply(htmltools::HTML)
    month_selected() %&gt;%
      st_transform(crs = &quot;+init=epsg:4326&quot;) %&gt;%
      leaflet() %&gt;%
      addProviderTiles(provider = &quot;CartoDB.Positron&quot;) %&gt;%
      setView(-73.9, 40.7, zoom = 10) %&gt;%
      addPolygons(label = labels,
                  stroke = FALSE,
                  smoothFactor = 0.5,
                  opacity = 1,
                  fillOpacity = 0.7,
                  fillColor = ~ pal(month_selected()$crime_counts),
                  highlightOptions = highlightOptions(weight = 5,
                                                      fillOpacity = 1,
                                                      color = &quot;black&quot;,
                                                      opacity = 1,
                                                      bringToFront = TRUE)) %&gt;%
      addLegend(&quot;bottomright&quot;,
                pal = pal,
                values = ~ crime_counts,
                title = &quot;Crime incident counts&quot;,
                opacity = 0.7)
  })
  output$crime_rate &lt;- renderLeaflet({
    pal &lt;- colorBin(palette = &quot;OrRd&quot;, 9, domain = crime_month$crime_rate * 10000)
    labels = sprintf(
      &quot;&lt;strong&gt;%s&lt;/strong&gt;&lt;br/&gt;%g incidents per 10 thousand residents&lt;br/&gt;during the 4 weeks period&quot;,
      month_selected()$modzcta, month_selected()$crime_rate * 10000) %&gt;%
      lapply(htmltools::HTML)
    month_selected() %&gt;%
      st_transform(crs = &quot;+init=epsg:4326&quot;) %&gt;%
      leaflet() %&gt;%
      addProviderTiles(provider = &quot;CartoDB.Positron&quot;) %&gt;%
      setView(-73.9, 40.7, zoom = 10) %&gt;%
      addPolygons(label = labels,
                  stroke = FALSE,
                  smoothFactor = 0.5,
                  opacity = 1,
                  fillOpacity = 0.7,
                  fillColor = ~ pal(month_selected()$crime_rate * 10000),
                  highlightOptions = highlightOptions(weight = 5,
                                                      fillOpacity = 1,
                                                      color = &quot;black&quot;,
                                                      opacity = 1,
                                                      bringToFront = TRUE)) %&gt;%
      addLegend(&quot;bottomright&quot;,
                pal = pal,
                values = ~ crime_rate,
                title = &quot;Crime incident rate&lt;br/&gt;(incidents per 10 thousand residents)&quot;,
                opacity = 0.7)
  })
}

shinyApp(ui = ui, server = server)</code></pre>
</div>
<div id="offenses-shiny" class="section level4">
<h4>Offenses Shiny</h4>
<p>This Shiny dashboard reports number of offenses based on their
categories in NYC based on selected borough, hour of the day, days of
the week, and season of the year. You can select different times and
location to see what kind of offenses are mostly likely to be committed
in these five boroughs during different hours of the day, days of the
week, and seasons of the year. The number of offenses are sorted in
descending order. The Shiny dashboard can be accessed <a
href="https://zz2780.shinyapps.io/final_shiny/">here</a>.</p>
<pre class="r"><code>crime_df &lt;- read.csv(&quot;data/crime_df.csv&quot;)%&gt;%
  mutate(
    season=case_when(
      mon %in% c(6,7,8)~&quot;Summer&quot;,
      mon %in% c(9,10,11)~&quot;Fall&quot;,
      mon %in% c(12,1,2)~&quot;Winter&quot;,
      mon %in% c(3,4,5)~&quot;Spring&quot;,
      )
    
  )

boros = crime_df %&gt;% distinct(borough) %&gt;% pull()

# selectInput widget
selectInput(
  &quot;boro_choice&quot;, 
  label = h3(&quot;Select borough&quot;),
  choices = boros, selected = &quot;Manhattan&quot;)

max_hour = 23
min_hour = 0
  
# sliderInput widget
sliderInput(
  &quot;hour_of_day_choice&quot;, 
  label = h3(&quot;Choose hour of the day&quot;), 
  min = min_hour, max = max_hour, value = c(17, 18))

day_week = crime_df %&gt;% distinct(day_of_week) %&gt;% pull()

# radioButtons widget
radioButtons(
  &quot;day_of_week_choice&quot;, 
  label = h3(&quot;Choose day of the week&quot;),
  choices = day_week, selected = &quot;Sunday&quot;)

season_choice = crime_df %&gt;% distinct(season) %&gt;% pull()
# radioButtons widget
radioButtons(
  &quot;season_choice&quot;, 
  label = h3(&quot;Choose season of the year&quot;),
  choices = season_choice, selected = &quot;Spring&quot;)

renderPlotly({
  crime_df %&gt;%
    filter(
    borough == input$boro_choice, 
    hour_of_day %in% input$hour_of_day_choice[1]:input$hour_of_day_choice[2],
    day_of_week == input$day_of_week_choice,
    season==input$season_choice) %&gt;%
  count(offense, name = &quot;offense_total&quot;) %&gt;%
  plot_ly(
    x = ~offense_total, y = ~reorder(offense, offense_total), type = &quot;bar&quot;)%&gt;%
    layout( xaxis = list(title = &quot;&quot;),
         yaxis = list(title = &quot;&quot;))
})</code></pre>
</div>
</div>
<div id="statistical-analysis" class="section level2">
<h2>Statistical Analysis</h2>
<div id="statistical-test" class="section level4">
<h4>Statistical test</h4>
</div>
<div id="chi-squared-test-on-year-and-number-of-cases-each-month."
class="section level4">
<h4>Chi-squared test on year and number of cases each month.</h4>
<p>We want to explore more on our data. So we conducted some statistical
test. First, we conducted a Chi-squared test on year and number of cases
each month to check whether the distribution of number of cases per
month is different between the two years.</p>
<p><span class="math inline">\(H_0\)</span> : The number distribution of
number of crime cases of each month was the same in 2016 and 2017</p>
<p><span class="math inline">\(H_1\)</span> : The number distribution of
number of crime cases of each month was different in 2016 and 2017</p>
<pre class="r"><code>df_1 &lt;- crime_df %&gt;%
  mutate (
    year = year(date)
  )

table(df_1$year, df_1 $mon)%&gt;%
  knitr::kable(digits = 3)</code></pre>
<table style="width:100%;">
<colgroup>
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">1</th>
<th align="right">2</th>
<th align="right">3</th>
<th align="right">4</th>
<th align="right">5</th>
<th align="right">6</th>
<th align="right">7</th>
<th align="right">8</th>
<th align="right">9</th>
<th align="right">10</th>
<th align="right">11</th>
<th align="right">12</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">2016</td>
<td align="right">5143</td>
<td align="right">4537</td>
<td align="right">5224</td>
<td align="right">5248</td>
<td align="right">5510</td>
<td align="right">5450</td>
<td align="right">5482</td>
<td align="right">5660</td>
<td align="right">5309</td>
<td align="right">5394</td>
<td align="right">4978</td>
<td align="right">4998</td>
</tr>
<tr class="even">
<td align="left">2017</td>
<td align="right">5226</td>
<td align="right">4370</td>
<td align="right">4912</td>
<td align="right">5097</td>
<td align="right">5589</td>
<td align="right">5481</td>
<td align="right">5753</td>
<td align="right">5696</td>
<td align="right">5756</td>
<td align="right">5996</td>
<td align="right">5667</td>
<td align="right">6595</td>
</tr>
</tbody>
</table>
<pre class="r"><code>chisq.test(table(df_1$year, df_1 $mon))</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  table(df_1$year, df_1$mon)
## X-squared = 258, df = 11, p-value &lt;2e-16</code></pre>
<p>As the result told us, the p-value &lt; 0.05 , therefore we reject
the null hypothesis and conclude that the distribution of number of
crimes cases of each month is significantly different between 2016 and
2017.</p>
</div>
<div id="anova-between-number-of-crimes-per-day-and-weather"
class="section level4">
<h4>ANOVA between number of crimes per day and weather</h4>
<p>We also concerned about whether weather conditions will affect New
York City’s crime frequency per day. Therefore it is important to test
hypotheses according to different weather conditions and crime cases per
day.</p>
<p>At first, we divided the daily weather into four categories (Not
rainy or snowy; rainy and snowy; snowy; rainy) according to whetherthe
precipitation and rainfall are greater than 0.</p>
<pre class="r"><code>crime_weather_2 &lt;-  crime_weather %&gt;%
  mutate(weather = case_when(mean_prcp == 0 &amp; mean_snow == 0 ~ &#39;not_rainy_or_snowy&#39;,
                           mean_prcp &gt;0 &amp; mean_snow &gt;0 ~ &#39;rainy_and_snowy&#39;,
                           mean_prcp == 0 &amp; mean_snow &gt;0 ~ &#39;snowy&#39;,
                           mean_prcp &gt;0 &amp; mean_snow == 0 ~ &quot;rainy&quot;)) %&gt;%
  select(date, total_crime,  weather)

crime_weather_2 %&gt;%
  group_by(weather)%&gt;%
  summarise(mean_daily_crime = mean(total_crime),
  Standard_deviation = sd(total_crime)) %&gt;%
  knitr::kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">weather</th>
<th align="right">mean_daily_crime</th>
<th align="right">Standard_deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">not_rainy_or_snowy</td>
<td align="right">180</td>
<td align="right">27.7</td>
</tr>
<tr class="even">
<td align="left">rainy</td>
<td align="right">176</td>
<td align="right">25.4</td>
</tr>
<tr class="odd">
<td align="left">rainy_and_snowy</td>
<td align="right">150</td>
<td align="right">36.3</td>
</tr>
<tr class="even">
<td align="left">snowy</td>
<td align="right">156</td>
<td align="right">21.1</td>
</tr>
</tbody>
</table>
<p>We then conducted one-way ANOVA to test if the true mean daily crime
cases of different weather is the same.</p>
<p><span class="math inline">\(H_0\)</span>: There is no difference in
the average number of crimes per day under different weather conditions
in New York.</p>
<p><span class="math inline">\(H_1\)</span>: At least the average number
of crimes per day under two different weather conditions are
different.</p>
<p>First, Let’s create box-plot of our data.</p>
<pre class="r"><code>ggplot(data = crime_weather_2, aes(x = weather, y = total_crime, fill = weather)) + geom_boxplot()</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-1.png" width="768" /></p>
<p>From the plot, the distribution of daily crime number seems different
in different weather.</p>
<p>And we conducted a ANOVA test</p>
<pre class="r"><code>res.aov &lt;- aov(total_crime ~ weather, data = crime_weather_2)
summary(res.aov) </code></pre>
<pre><code>##              Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## weather       3  31642   10547    14.5 3.7e-09 ***
## Residuals   727 530437     730                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>From the result, the p-value is smaller than 0.05, therefore we
concluded that the average number of crimes per day is correlated to
weather.</p>
</div>
<div
id="chi-squared-test-on-weather-and-number-of-different-types-of-offense"
class="section level4">
<h4>Chi-squared test on weather and number of different types of
offense</h4>
<p>We want to investigate whether weather is a significant factor on
number of offenses. We combine the two dataset and create a categorical
variable according to the weather parameters each day and divided them
into four types: “rainy and snowy”, “snowy”, “rainy”, “not rainy or
snowy”.</p>
<pre class="r"><code>crime_weather_3 = crime %&gt;%
  merge(weather_df , by = &quot;date&quot;)%&gt;%
  mutate(weather = case_when(mean_prcp == 0 &amp; mean_snow == 0 ~ &#39;not_rainy_or_snowy&#39;,
                           mean_prcp &gt;0 &amp; mean_snow &gt;0 ~ &#39;rainy_and_snowy&#39;,
                           mean_prcp == 0 &amp; mean_snow &gt;0 ~ &#39;snowy&#39;,
                           mean_prcp &gt;0 &amp; mean_snow == 0 ~ &quot;rainy&quot;)) 

df_crime_weather &lt;- crime_weather_3 %&gt;%
  group_by(weather, offense) %&gt;%
  summarise(Total_number_of_offense = n()) %&gt;%
  pivot_wider(
    names_from = &quot;weather&quot;,
    values_from = &quot;Total_number_of_offense&quot;
  ) 
df_crime_weather[is.na(df_crime_weather)] = 0
df_crime_weather %&gt;%
  head(20) %&gt;%
  knitr::kable(digits = 3)</code></pre>
<table style="width:100%;">
<colgroup>
<col width="44%" />
<col width="22%" />
<col width="7%" />
<col width="19%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">offense</th>
<th align="right">not_rainy_or_snowy</th>
<th align="right">rainy</th>
<th align="right">rainy_and_snowy</th>
<th align="right">snowy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"></td>
<td align="right">3</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">ADMINISTRATIVE CODE</td>
<td align="right">142</td>
<td align="right">94</td>
<td align="right">5</td>
<td align="right">4</td>
</tr>
<tr class="odd">
<td align="left">ADMINISTRATIVE CODES</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">AGRICULTURE &amp; MRKTS LAW-UNCLASSIFIED</td>
<td align="right">16</td>
<td align="right">10</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">ALCOHOLIC BEVERAGE CONTROL LAW</td>
<td align="right">15</td>
<td align="right">7</td>
<td align="right">0</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td align="left">ANTICIPATORY OFFENSES</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">ARSON</td>
<td align="right">110</td>
<td align="right">55</td>
<td align="right">4</td>
<td align="right">12</td>
</tr>
<tr class="even">
<td align="left">ASSAULT 3 &amp; RELATED OFFENSES</td>
<td align="right">8185</td>
<td align="right">4708</td>
<td align="right">329</td>
<td align="right">492</td>
</tr>
<tr class="odd">
<td align="left">BURGLAR’S TOOLS</td>
<td align="right">44</td>
<td align="right">20</td>
<td align="right">4</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left">BURGLARY</td>
<td align="right">1949</td>
<td align="right">1199</td>
<td align="right">83</td>
<td align="right">127</td>
</tr>
<tr class="odd">
<td align="left">CHILD ABANDONMENT/NON SUPPORT</td>
<td align="right">7</td>
<td align="right">1</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">CRIMINAL MISCHIEF &amp; RELATED OF</td>
<td align="right">7904</td>
<td align="right">4688</td>
<td align="right">331</td>
<td align="right">415</td>
</tr>
<tr class="odd">
<td align="left">CRIMINAL TRESPASS</td>
<td align="right">516</td>
<td align="right">336</td>
<td align="right">35</td>
<td align="right">47</td>
</tr>
<tr class="even">
<td align="left">DANGEROUS DRUGS</td>
<td align="right">3602</td>
<td align="right">1935</td>
<td align="right">147</td>
<td align="right">210</td>
</tr>
<tr class="odd">
<td align="left">DANGEROUS WEAPONS</td>
<td align="right">1550</td>
<td align="right">858</td>
<td align="right">80</td>
<td align="right">88</td>
</tr>
<tr class="even">
<td align="left">DISORDERLY CONDUCT</td>
<td align="right">14</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">ENDAN WELFARE INCOMP</td>
<td align="right">4</td>
<td align="right">7</td>
<td align="right">1</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">ESCAPE 3</td>
<td align="right">3</td>
<td align="right">2</td>
<td align="right">0</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">FELONY ASSAULT</td>
<td align="right">3257</td>
<td align="right">1819</td>
<td align="right">127</td>
<td align="right">195</td>
</tr>
<tr class="even">
<td align="left">FORGERY</td>
<td align="right">975</td>
<td align="right">504</td>
<td align="right">44</td>
<td align="right">57</td>
</tr>
</tbody>
</table>
<p>We also conducted a Chi-squared test on number of different types of
crimes and weather.</p>
<p><span class="math inline">\(H_0\)</span> : The number distribution of
each type of crime was the same in different weathers.</p>
<p><span class="math inline">\(H_1\)</span> : The number distribution of
each type of crime was different in different weathers.</p>
<pre class="r"><code>chisq.test(table(crime_weather_3$weather, crime_weather_3$offense))</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  table(crime_weather_3$weather, crime_weather_3$offense)
## X-squared = 224, df = 171, p-value = 0.004</code></pre>
<p>We can see p-value is smaller than 0.05, so we reject the null
hypothesis and conclude that there’s at least one type of weather’s
proportions of number of different type of crimes is different from
others at 0.05 significant level.<br />
We learned from the result that there is not a homogeneity in the types
of crimes for each type of weather. So we conclude that weather may also
has an association with the type of crimes.</p>
</div>
</div>
<div id="modeling" class="section level2">
<h2>Modeling</h2>
<p>Based on some publicly available information, we knew that weather
affect crime rate. For example, the hotter the weather is, the more
likely people are to commit crimes. The worse the weather is, the less
likely people are to go out and commit crimes. Here we want to predict
number of crimes each day in New York as our outcome. And the
precipitation, snow depth, maximum temperature and minimum temperature
can be considered as predictors.</p>
<p>First, let’s check the distribution of number of crime cases each day
in New York.</p>
<pre class="r"><code>ggplot(data = crime_weather,aes(x = total_crime)) + geom_histogram()+ 
  labs(title = &quot;The distribution of daily cases&quot;, 
       y = &quot;Counts&quot;, 
       x = &quot;Number of crimes per day&quot;)+
  theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-26-1.png" width="768" /></p>
<p>From the distribution of daily cases, we noticed that it is
approximately normally distributed, therefore we don’t need to transform
the value of the outcome.</p>
<p>Then, we use scatter plot to investigate the association between
weather and cases/crime.</p>
<pre class="r"><code>ggplot(crime_weather, aes(x = mean_tmax, y = total_crime)) + geom_point()+    labs(title = &quot;The Association between Max temperatures and reported crime&quot;, 
       y = &quot;Total Crime reported&quot;, 
       x = &quot;Max temperatures of a day&quot;)+
    theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-27-1.png" width="768" /></p>
<pre class="r"><code>ggplot(crime_weather, aes(x = mean_tmin, y = total_crime)) + geom_point()+    labs(title = &quot;The Association between Min temperatures and reported crime&quot;, 
       y = &quot;Total Crime reported&quot;, 
       x = &quot;Min temperatures of a day&quot;)+
    theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-27-2.png" width="768" /></p>
<pre class="r"><code>ggplot(crime_weather, aes(x = mean_prcp, y = total_crime)) + geom_point()+    labs(title = &quot;The Association between precipitation and reported crime&quot;,
       y = &quot;Total Crime reported&quot;, 
       x = &quot;Precipitation(tenths of mm)&quot;)+
    theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-27-3.png" width="768" /></p>
<pre class="r"><code>ggplot(crime_weather, aes(x = mean_snow, y = total_crime)) + geom_point()+    labs(title = &quot;The Association between snowfall and reported crime&quot;,
       y = &quot;Total Crime reported&quot;, 
       x = &quot;Snow depth(mm)&quot;)+
    theme(plot.title = element_text(hjust = 0.5))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-27-4.png" width="768" /></p>
<p>From the plots, we noticed that all of the four predictors may have
association with the number of cases of crime in New York, So I proposed
the following models. We also want to investigate whether the month and
day of week can be predictors.</p>
<div id="fitting-model" class="section level4">
<h4>Fitting Model</h4>
<p>Firstly, I use month, weekdays and all weather data as predictors</p>
<pre class="r"><code>full_model = lm(total_crime ~ month + day_of_week + mean_tmin + mean_tmax + mean_prcp + mean_snow, data = crime_weather)
summary(full_model) %&gt;%
  broom::tidy() %&gt;%
  knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">184.26</td>
<td align="right">4.59</td>
<td align="right">40.12</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">month2</td>
<td align="right">-16.48</td>
<td align="right">4.56</td>
<td align="right">-3.62</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">month3</td>
<td align="right">-12.26</td>
<td align="right">4.54</td>
<td align="right">-2.70</td>
<td align="right">0.01</td>
</tr>
<tr class="even">
<td align="left">month4</td>
<td align="right">-8.69</td>
<td align="right">4.95</td>
<td align="right">-1.76</td>
<td align="right">0.08</td>
</tr>
<tr class="odd">
<td align="left">month5</td>
<td align="right">-3.77</td>
<td align="right">5.33</td>
<td align="right">-0.71</td>
<td align="right">0.48</td>
</tr>
<tr class="even">
<td align="left">month6</td>
<td align="right">-6.89</td>
<td align="right">6.13</td>
<td align="right">-1.12</td>
<td align="right">0.26</td>
</tr>
<tr class="odd">
<td align="left">month7</td>
<td align="right">-8.76</td>
<td align="right">6.66</td>
<td align="right">-1.31</td>
<td align="right">0.19</td>
</tr>
<tr class="even">
<td align="left">month8</td>
<td align="right">-7.80</td>
<td align="right">6.59</td>
<td align="right">-1.18</td>
<td align="right">0.24</td>
</tr>
<tr class="odd">
<td align="left">month9</td>
<td align="right">-4.40</td>
<td align="right">6.11</td>
<td align="right">-0.72</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">month10</td>
<td align="right">0.89</td>
<td align="right">5.34</td>
<td align="right">0.17</td>
<td align="right">0.87</td>
</tr>
<tr class="odd">
<td align="left">month11</td>
<td align="right">-0.78</td>
<td align="right">4.71</td>
<td align="right">-0.17</td>
<td align="right">0.87</td>
</tr>
<tr class="even">
<td align="left">month12</td>
<td align="right">14.51</td>
<td align="right">4.47</td>
<td align="right">3.24</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekMonday</td>
<td align="right">-24.58</td>
<td align="right">3.35</td>
<td align="right">-7.33</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekSaturday</td>
<td align="right">-17.01</td>
<td align="right">3.34</td>
<td align="right">-5.09</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekSunday</td>
<td align="right">-25.66</td>
<td align="right">3.34</td>
<td align="right">-7.67</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekThursday</td>
<td align="right">-14.85</td>
<td align="right">3.36</td>
<td align="right">-4.43</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekTuesday</td>
<td align="right">-16.45</td>
<td align="right">3.36</td>
<td align="right">-4.90</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekWednesday</td>
<td align="right">-8.54</td>
<td align="right">3.36</td>
<td align="right">-2.54</td>
<td align="right">0.01</td>
</tr>
<tr class="odd">
<td align="left">mean_tmin</td>
<td align="right">0.03</td>
<td align="right">0.42</td>
<td align="right">0.06</td>
<td align="right">0.95</td>
</tr>
<tr class="even">
<td align="left">mean_tmax</td>
<td align="right">0.77</td>
<td align="right">0.35</td>
<td align="right">2.18</td>
<td align="right">0.03</td>
</tr>
<tr class="odd">
<td align="left">mean_prcp</td>
<td align="right">-0.05</td>
<td align="right">0.01</td>
<td align="right">-4.29</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">mean_snow</td>
<td align="right">-0.08</td>
<td align="right">0.02</td>
<td align="right">-3.55</td>
<td align="right">0.00</td>
</tr>
</tbody>
</table>
<p>I noticed that both tmax and tmin are not significant, which may be
attributed to their correlation, so I calculated the VIF.</p>
<pre class="r"><code>vif(full_model) %&gt;%
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">GVIF</th>
<th align="right">Df</th>
<th align="right">GVIF^(1/(2*Df))</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">month</td>
<td align="right">6.31</td>
<td align="right">11</td>
<td align="right">1.09</td>
</tr>
<tr class="even">
<td align="left">day_of_week</td>
<td align="right">1.05</td>
<td align="right">6</td>
<td align="right">1.00</td>
</tr>
<tr class="odd">
<td align="left">mean_tmin</td>
<td align="right">18.24</td>
<td align="right">1</td>
<td align="right">4.27</td>
</tr>
<tr class="even">
<td align="left">mean_tmax</td>
<td align="right">14.84</td>
<td align="right">1</td>
<td align="right">3.85</td>
</tr>
<tr class="odd">
<td align="left">mean_prcp</td>
<td align="right">1.08</td>
<td align="right">1</td>
<td align="right">1.04</td>
</tr>
<tr class="even">
<td align="left">mean_snow</td>
<td align="right">1.15</td>
<td align="right">1</td>
<td align="right">1.07</td>
</tr>
</tbody>
</table>
<p>It is obvious that the VIF of tmin and tmax is high, so I chose to
drop tmin. Besides, I found that some months are not significantly
different from the reference category. So, what if we drop the
month?</p>
<p>The second proposed model is total_crime ~ day_of_week + mean_tmax +
mean_prcp + mean_snow</p>
<pre class="r"><code>model1 = lm(total_crime ~  day_of_week + mean_tmax + mean_prcp + mean_snow, data = crime_weather)
summary(model1) %&gt;%
  broom::tidy() %&gt;%
  knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">183.55</td>
<td align="right">3.04</td>
<td align="right">60.31</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekMonday</td>
<td align="right">-24.79</td>
<td align="right">3.47</td>
<td align="right">-7.14</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekSaturday</td>
<td align="right">-17.05</td>
<td align="right">3.46</td>
<td align="right">-4.93</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekSunday</td>
<td align="right">-25.61</td>
<td align="right">3.47</td>
<td align="right">-7.39</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekThursday</td>
<td align="right">-14.98</td>
<td align="right">3.48</td>
<td align="right">-4.31</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekTuesday</td>
<td align="right">-16.60</td>
<td align="right">3.47</td>
<td align="right">-4.78</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekWednesday</td>
<td align="right">-8.71</td>
<td align="right">3.48</td>
<td align="right">-2.50</td>
<td align="right">0.01</td>
</tr>
<tr class="even">
<td align="left">mean_tmax</td>
<td align="right">0.59</td>
<td align="right">0.10</td>
<td align="right">6.00</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">mean_prcp</td>
<td align="right">-0.05</td>
<td align="right">0.01</td>
<td align="right">-4.40</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">mean_snow</td>
<td align="right">-0.09</td>
<td align="right">0.02</td>
<td align="right">-3.89</td>
<td align="right">0.00</td>
</tr>
</tbody>
</table>
<p>This time, the tmax becomes significant. And it has a positive effect
on crime rate, which validate our assumption. Besides, all other
variables are significant.</p>
<p>But we noticed that some months are significantly different from
reference catergory, so we want to compare model1 and model with
month.</p>
<pre class="r"><code>model2 = lm(total_crime ~ month +day_of_week +  mean_tmax + mean_prcp + mean_snow, data = crime_weather)
summary(model2) %&gt;%
  broom::tidy() %&gt;%
  knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">184.14</td>
<td align="right">4.14</td>
<td align="right">44.47</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">month2</td>
<td align="right">-16.51</td>
<td align="right">4.53</td>
<td align="right">-3.64</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">month3</td>
<td align="right">-12.28</td>
<td align="right">4.52</td>
<td align="right">-2.72</td>
<td align="right">0.01</td>
</tr>
<tr class="even">
<td align="left">month4</td>
<td align="right">-8.68</td>
<td align="right">4.94</td>
<td align="right">-1.76</td>
<td align="right">0.08</td>
</tr>
<tr class="odd">
<td align="left">month5</td>
<td align="right">-3.71</td>
<td align="right">5.24</td>
<td align="right">-0.71</td>
<td align="right">0.48</td>
</tr>
<tr class="even">
<td align="left">month6</td>
<td align="right">-6.80</td>
<td align="right">5.94</td>
<td align="right">-1.14</td>
<td align="right">0.25</td>
</tr>
<tr class="odd">
<td align="left">month7</td>
<td align="right">-8.62</td>
<td align="right">6.30</td>
<td align="right">-1.37</td>
<td align="right">0.17</td>
</tr>
<tr class="even">
<td align="left">month8</td>
<td align="right">-7.66</td>
<td align="right">6.18</td>
<td align="right">-1.24</td>
<td align="right">0.22</td>
</tr>
<tr class="odd">
<td align="left">month9</td>
<td align="right">-4.28</td>
<td align="right">5.82</td>
<td align="right">-0.74</td>
<td align="right">0.46</td>
</tr>
<tr class="even">
<td align="left">month10</td>
<td align="right">0.95</td>
<td align="right">5.23</td>
<td align="right">0.18</td>
<td align="right">0.86</td>
</tr>
<tr class="odd">
<td align="left">month11</td>
<td align="right">-0.77</td>
<td align="right">4.70</td>
<td align="right">-0.16</td>
<td align="right">0.87</td>
</tr>
<tr class="even">
<td align="left">month12</td>
<td align="right">14.51</td>
<td align="right">4.47</td>
<td align="right">3.25</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekMonday</td>
<td align="right">-24.59</td>
<td align="right">3.35</td>
<td align="right">-7.35</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekSaturday</td>
<td align="right">-17.01</td>
<td align="right">3.34</td>
<td align="right">-5.09</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekSunday</td>
<td align="right">-25.66</td>
<td align="right">3.34</td>
<td align="right">-7.68</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekThursday</td>
<td align="right">-14.85</td>
<td align="right">3.35</td>
<td align="right">-4.43</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekTuesday</td>
<td align="right">-16.43</td>
<td align="right">3.35</td>
<td align="right">-4.91</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekWednesday</td>
<td align="right">-8.54</td>
<td align="right">3.36</td>
<td align="right">-2.54</td>
<td align="right">0.01</td>
</tr>
<tr class="odd">
<td align="left">mean_tmax</td>
<td align="right">0.79</td>
<td align="right">0.19</td>
<td align="right">4.15</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">mean_prcp</td>
<td align="right">-0.05</td>
<td align="right">0.01</td>
<td align="right">-4.37</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">mean_snow</td>
<td align="right">-0.08</td>
<td align="right">0.02</td>
<td align="right">-3.57</td>
<td align="right">0.00</td>
</tr>
</tbody>
</table>
<pre class="r"><code>anova(model1, model2)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Model 1: total_crime ~ day_of_week + mean_tmax + mean_prcp + mean_snow
## Model 2: total_crime ~ month + day_of_week + mean_tmax + mean_prcp + mean_snow
##   Res.Df    RSS Df Sum of Sq    F  Pr(&gt;F)    
## 1    721 453378                              
## 2    710 414710 11     38669 6.02 1.9e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>We use ANOVA to compare the two models. Since p-value is smaller than
0.05, we should include month in our model.</p>
<p>We also want to try to include a interaction term in our model.</p>
<pre class="r"><code>model3 &lt;- lm(total_crime ~  month +day_of_week +  mean_tmax + mean_prcp + mean_snow + mean_tmax*day_of_week, data = crime_weather )
summary(model3) %&gt;%
    broom::tidy() %&gt;%
  knitr::kable(digits = 2)</code></pre>
<table>
<colgroup>
<col width="45%" />
<col width="13%" />
<col width="14%" />
<col width="14%" />
<col width="11%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">191.12</td>
<td align="right">5.59</td>
<td align="right">34.20</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">month2</td>
<td align="right">-16.88</td>
<td align="right">4.53</td>
<td align="right">-3.73</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">month3</td>
<td align="right">-12.64</td>
<td align="right">4.52</td>
<td align="right">-2.80</td>
<td align="right">0.01</td>
</tr>
<tr class="even">
<td align="left">month4</td>
<td align="right">-9.17</td>
<td align="right">4.94</td>
<td align="right">-1.86</td>
<td align="right">0.06</td>
</tr>
<tr class="odd">
<td align="left">month5</td>
<td align="right">-4.30</td>
<td align="right">5.24</td>
<td align="right">-0.82</td>
<td align="right">0.41</td>
</tr>
<tr class="even">
<td align="left">month6</td>
<td align="right">-7.55</td>
<td align="right">5.95</td>
<td align="right">-1.27</td>
<td align="right">0.20</td>
</tr>
<tr class="odd">
<td align="left">month7</td>
<td align="right">-9.48</td>
<td align="right">6.30</td>
<td align="right">-1.50</td>
<td align="right">0.13</td>
</tr>
<tr class="even">
<td align="left">month8</td>
<td align="right">-8.45</td>
<td align="right">6.19</td>
<td align="right">-1.37</td>
<td align="right">0.17</td>
</tr>
<tr class="odd">
<td align="left">month9</td>
<td align="right">-4.96</td>
<td align="right">5.83</td>
<td align="right">-0.85</td>
<td align="right">0.39</td>
</tr>
<tr class="even">
<td align="left">month10</td>
<td align="right">0.36</td>
<td align="right">5.23</td>
<td align="right">0.07</td>
<td align="right">0.94</td>
</tr>
<tr class="odd">
<td align="left">month11</td>
<td align="right">-1.06</td>
<td align="right">4.70</td>
<td align="right">-0.23</td>
<td align="right">0.82</td>
</tr>
<tr class="even">
<td align="left">month12</td>
<td align="right">14.02</td>
<td align="right">4.47</td>
<td align="right">3.14</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekMonday</td>
<td align="right">-36.77</td>
<td align="right">6.94</td>
<td align="right">-5.30</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekSaturday</td>
<td align="right">-25.17</td>
<td align="right">6.57</td>
<td align="right">-3.83</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekSunday</td>
<td align="right">-29.43</td>
<td align="right">6.75</td>
<td align="right">-4.36</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekThursday</td>
<td align="right">-27.26</td>
<td align="right">6.97</td>
<td align="right">-3.91</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekTuesday</td>
<td align="right">-27.93</td>
<td align="right">6.95</td>
<td align="right">-4.02</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekWednesday</td>
<td align="right">-9.17</td>
<td align="right">7.14</td>
<td align="right">-1.28</td>
<td align="right">0.20</td>
</tr>
<tr class="odd">
<td align="left">mean_tmax</td>
<td align="right">0.42</td>
<td align="right">0.28</td>
<td align="right">1.50</td>
<td align="right">0.13</td>
</tr>
<tr class="even">
<td align="left">mean_prcp</td>
<td align="right">-0.05</td>
<td align="right">0.01</td>
<td align="right">-4.22</td>
<td align="right">0.00</td>
</tr>
<tr class="odd">
<td align="left">mean_snow</td>
<td align="right">-0.08</td>
<td align="right">0.02</td>
<td align="right">-3.59</td>
<td align="right">0.00</td>
</tr>
<tr class="even">
<td align="left">day_of_weekMonday:mean_tmax</td>
<td align="right">0.69</td>
<td align="right">0.34</td>
<td align="right">2.01</td>
<td align="right">0.05</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekSaturday:mean_tmax</td>
<td align="right">0.47</td>
<td align="right">0.33</td>
<td align="right">1.43</td>
<td align="right">0.15</td>
</tr>
<tr class="even">
<td align="left">day_of_weekSunday:mean_tmax</td>
<td align="right">0.21</td>
<td align="right">0.33</td>
<td align="right">0.64</td>
<td align="right">0.52</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekThursday:mean_tmax</td>
<td align="right">0.69</td>
<td align="right">0.34</td>
<td align="right">2.04</td>
<td align="right">0.04</td>
</tr>
<tr class="even">
<td align="left">day_of_weekTuesday:mean_tmax</td>
<td align="right">0.65</td>
<td align="right">0.34</td>
<td align="right">1.89</td>
<td align="right">0.06</td>
</tr>
<tr class="odd">
<td align="left">day_of_weekWednesday:mean_tmax</td>
<td align="right">0.06</td>
<td align="right">0.34</td>
<td align="right">0.17</td>
<td align="right">0.86</td>
</tr>
</tbody>
</table>
<p>In model 3 , we assume that there is an interaction between
temperature and day of week. However, some of the interaction term are
not significant.</p>
<p>We also want to know whether to include months and weekdays in our
model.</p>
<pre class="r"><code>model4 &lt;- lm(total_crime ~ mean_tmax + mean_prcp + mean_snow, data = crime_weather)
summary(model4) %&gt;%
  broom::tidy() %&gt;%
  knitr::kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">168.17</td>
<td align="right">2.15</td>
<td align="right">78.15</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">mean_tmax</td>
<td align="right">0.59</td>
<td align="right">0.10</td>
<td align="right">5.76</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">mean_prcp</td>
<td align="right">-0.05</td>
<td align="right">0.01</td>
<td align="right">-4.31</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">mean_snow</td>
<td align="right">-0.09</td>
<td align="right">0.02</td>
<td align="right">-4.05</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
</div>
<div id="cross-validation" class="section level4">
<h4>Cross Validation</h4>
<p>We want to decide which model is the best to predict the daily number
of crime cases in New York. We use cross validation to compare the
models.</p>
<pre class="r"><code>cv_df &lt;- 
  crossv_mc(crime_weather, 100) %&gt;%  
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)
  )</code></pre>
<pre class="r"><code>cv_df &lt;- 
  cv_df %&gt;% 
  mutate(
    model1 = map( train, ~lm(total_crime ~ month + day_of_week + mean_tmax + mean_prcp + mean_snow, data = crime_weather)),
    model2 =  map( train, ~lm(total_crime ~ day_of_week +  mean_tmax + mean_prcp+mean_snow, data = crime_weather)),
    model3 =  map( train, ~lm(total_crime ~ month +day_of_week +  mean_tmax + mean_prcp + mean_snow +mean_tmax*day_of_week, data = crime_weather)),
    model4 = map( train, ~lm( total_crime ~ mean_tmax + mean_prcp + mean_snow, data = crime_weather))) %&gt;%
   mutate(
    rmse_model1 = map2_dbl( model1,  test, ~rmse(model = .x, data =.y)),
    rmse_model2 = map2_dbl( model2,  test, ~rmse(model = .x, data =.y)),
    rmse_model3 = map2_dbl( model3,  test, ~rmse(model = .x, data =.y)),
    rmse_model4 = map2_dbl( model4, test, ~rmse(model = .x, data =.y))
  ) </code></pre>
<pre class="r"><code>cv_df %&gt;% 
  select(starts_with(&quot;rmse&quot;)) %&gt;% 
  pivot_longer(
    everything(),
    names_to = &quot;model&quot;, 
    values_to = &quot;rmse&quot;,
    names_prefix = &quot;rmse_&quot;) %&gt;% 
  mutate(model = fct_inorder(model)) %&gt;% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-36-1.png" width="768" /></p>
<pre class="r"><code>cv_df %&gt;% 
  summarize(
    rmse_1 = mean(rmse_model1),
    rmse_2 = mean(rmse_model2),
    rmse_3 = mean(rmse_model3),
    rmse_4 = mean(rmse_model4)
  ) %&gt;%
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">rmse_1</th>
<th align="right">rmse_2</th>
<th align="right">rmse_3</th>
<th align="right">rmse_4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">24.1</td>
<td align="right">25.2</td>
<td align="right">24</td>
<td align="right">26.6</td>
</tr>
</tbody>
</table>
</div>
<div id="model-diagnostics" class="section level4">
<h4>Model Diagnostics</h4>
<pre class="r"><code>par(mfrow = c(2,2))
plot(model3)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-37-1.png" width="768" /></p>
<p>Model3’s root means square error is the smallest in the four models,
which may indicates it is the best model in the four models.</p>
<p>We then did a model diagnostic to check if the model assumptions.
Although there are some outliers as shown in the plots, the Q-Q plot,
residuals VS fitted plot and Scale-Location plot indicates the residuals
are normally distributed and variance of residuals is constant.
Therefore, model3 could be useful for predicting the total number of
crime cases each day in New York, which means month, day of week,
temperature, precipitation , snow depth and a interaction term between
day of week and temperature are all useful predictors if we want to
predict the number of crime cases on a specific day in New York.</p>
</div>
</div>
<div id="discussion" class="section level2">
<h2>Discussion</h2>
<p>We established 4 models aiming to predict how weather contributes to
crime occurrence in NYC, and chose a final model with cross validation
and assumption diagnostics with standard criterions of linear
regression. Model 3 is our best model because it has the lowest RMSE
value among all models. Months (excluding October and December), day of
week (excluding Friday), average precipitation, average snow fall are a
series of predictors that affect crime occurrence with negative slopes.
Months (October and December), average maximum temperature, and the
interaction terms between average maximum temperature and days within a
week are a series of predictors that affect crime occurrence with
positive slopes. Since days within a week alone have negative slopes,
while their interaction between average maximum temperature are having
positive slopes, a higher temperature may have more to do with higher
crime occurrence. To illustrate, research articles has confirmed that a
slight raise in average temperatures will increase violent crime rates
when other contributing factors are constant (Tiihonen et al., 2017).
This can be seen in the Month predictors as they are less negative in
May, June, July, August, and September.</p>
<p>However, there is a inconsistency in the Month predictors because
October and December are having positive slopes, while November has a
slope of -1.06 which is higher than the slopes of May-September. This
may be caused by other factors that are not included in our datasets,
such as holidays – our guesses are people may tend to commit more crimes
during holiday seasons for money, and there are more people out of
town/visiting neighborhoods that they are not familiar with, which led
to problems. This may also be a result of data sampling error because
our dataset only included data from 2016 and 2017. The slopes are very
likely to be changed when we enlarge our sample.</p>
<p>The strength of our model is demonstrated by its relatively lower
RMSE (24) in cross validation, which represent certain accuracy of the
model in predicting the response comparing to the rest of our
models.</p>
<p>Limitations exist in our model. First, as we mentioned above, our
data were collected from 2016 and 2017, which is not representative of
the overall crime tendency in NYC. In addition, our model only included
factors that is weather/temperature relative, and the well-established
factors affecting crimes – such as poverty and mental health issues, are
not included or controlled at baseline in our study. Stratification of
demographical factors is necessary for accuracy. Furthermore, since our
aim is to predict the occurrence of crimes based on weather, a goodness
of fit should be evaluated carefully for such prediction. Other
selection criterions like Mallow’s Cp and adjusted R^2 may be included
in the model validation process. It is also important that a logical
selection procedure is strictly followed for statistical model
selection. Some variables may be log-transformed to become more
effective, and multicollinearity should be assessed to check for
confounders. In our model, such selection and assessments were not done.
These suggest that our model may lack some level of accuracy.</p>
<p>Tiihonen, J., Halonen, P., Tiihonen, L. et al. The Association of
Ambient Temperature and Violent Crime. Sci Rep 7, 6543 (2017). <a
href="https://doi.org/10.1038/s41598-017-06720-z"
class="uri">https://doi.org/10.1038/s41598-017-06720-z</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
