---
title: "Crime Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    souce_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(readr)
library(tidyverse)
library(plotly)

crime_df <- read.csv("data/crime_df.csv")%>%
  mutate(
    season=case_when(
      mon %in% c(6,7,8)~"Summer",
      mon %in% c(9,10,11)~"Fall",
      mon %in% c(12,1,2)~"Winter",
      mon %in% c(3,4,5)~"Spring",
      )
    
  )
```

## Column {.sidebar}

```{r}
boros = crime_df %>% distinct(borough) %>% pull()

# selectInput widget
selectInput(
  "boro_choice", 
  label = h3("Select borough"),
  choices = boros, selected = "Manhattan")

max_hour = 23
min_hour = 0
  
# sliderInput widget
sliderInput(
  "hour_of_day_choice", 
  label = h3("Choose hour of the day"), 
  min = min_hour, max = max_hour, value = c(17, 18))

day_week = crime_df %>% distinct(day_of_week) %>% pull()

# radioButtons widget
radioButtons(
  "day_of_week_choice", 
  label = h3("Choose day of the week"),
  choices = day_week, selected = "Sunday")

season_choice = crime_df %>% distinct(season) %>% pull()
# radioButtons widget
radioButtons(
  "season_choice", 
  label = h3("Choose season of the year"),
  choices = season_choice, selected = "Spring")
```

## Column

### Distribution of Offenses in New York City

```{r}
renderPlotly({
  crime_df %>%
    filter(
    borough == input$boro_choice, 
    hour_of_day %in% input$hour_of_day_choice[1]:input$hour_of_day_choice[2],
    day_of_week == input$day_of_week_choice,
    season==input$season_choice) %>%
  group_by(borough, hour_of_day, day_of_week,season)%>%
  count(offense, name = "offense_total") %>%
  arrange(desc(offense_total)) %>%
  plot_ly(
    x = ~offense_total, y = ~reorder(offense, offense_total), type = "bar", color = ~ offense, colors = "viridis")%>%
    layout( xaxis = list(title = ""),
         yaxis = list(title = ""))
})
```
